// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXwtmlWqNWJqFUkm4AK91BIX0igPH5-3o',
    appId: '1:323568304195:web:30ac6cc87d43aa9e1494f6',
    messagingSenderId: '323568304195',
    projectId: 'prakflutterfirebase-c7cb5',
    authDomain: 'prakflutterfirebase-c7cb5.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-c7cb5.appspot.com',
    measurementId: 'G-0JFNCKMC88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0RLo4-x0VrTdPp3fLoPWSCmY1QFpb3iU',
    appId: '1:323568304195:android:3d531a0873f64d281494f6',
    messagingSenderId: '323568304195',
    projectId: 'prakflutterfirebase-c7cb5',
    storageBucket: 'prakflutterfirebase-c7cb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwtRERaPkHuK95mFrEVWQE9001Pj5i8t8',
    appId: '1:323568304195:ios:588baf67389172181494f6',
    messagingSenderId: '323568304195',
    projectId: 'prakflutterfirebase-c7cb5',
    storageBucket: 'prakflutterfirebase-c7cb5.appspot.com',
    androidClientId: '323568304195-6h5mfcm3s6q4n4tqgecbm75euniarnln.apps.googleusercontent.com',
    iosClientId: '323568304195-gijo2r2fn880mfeimd8lbjs8eupp34sg.apps.googleusercontent.com',
    iosBundleId: 'com.example.praktikum9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwtRERaPkHuK95mFrEVWQE9001Pj5i8t8',
    appId: '1:323568304195:ios:588baf67389172181494f6',
    messagingSenderId: '323568304195',
    projectId: 'prakflutterfirebase-c7cb5',
    storageBucket: 'prakflutterfirebase-c7cb5.appspot.com',
    androidClientId: '323568304195-6h5mfcm3s6q4n4tqgecbm75euniarnln.apps.googleusercontent.com',
    iosClientId: '323568304195-gijo2r2fn880mfeimd8lbjs8eupp34sg.apps.googleusercontent.com',
    iosBundleId: 'com.example.praktikum9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXwtmlWqNWJqFUkm4AK91BIX0igPH5-3o',
    appId: '1:323568304195:web:90f71c362722ea561494f6',
    messagingSenderId: '323568304195',
    projectId: 'prakflutterfirebase-c7cb5',
    authDomain: 'prakflutterfirebase-c7cb5.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-c7cb5.appspot.com',
    measurementId: 'G-JJWD81KPXB',
  );

}